// Mocks generated by Mockito 5.4.6 from annotations
// in yds_vibe_app/test/study_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:yds_vibe_app/core/result.dart' as _i4;
import 'package:yds_vibe_app/models/card.dart' as _i5;
import 'package:yds_vibe_app/repositories/card_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CardRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCardRepository extends _i1.Mock implements _i2.CardRepository {
  MockCardRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.VocabularyCard>>> getAllCards() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCards, []),
            returnValue: _i3.Future<_i4.Result<List<_i5.VocabularyCard>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.VocabularyCard>>>(
                this,
                Invocation.method(#getAllCards, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.VocabularyCard>>>);

  @override
  _i3.Future<_i4.Result<List<_i5.VocabularyCard>>> getCardsByCategory(
    String? category,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCardsByCategory, [category]),
            returnValue: _i3.Future<_i4.Result<List<_i5.VocabularyCard>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.VocabularyCard>>>(
                this,
                Invocation.method(#getCardsByCategory, [category]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.VocabularyCard>>>);

  @override
  _i3.Future<_i4.Result<void>> saveCardProgress(_i5.VocabularyCard? card) =>
      (super.noSuchMethod(
            Invocation.method(#saveCardProgress, [card]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#saveCardProgress, [card]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> saveAllProgress(
    List<_i5.VocabularyCard>? cards,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveAllProgress, [cards]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#saveAllProgress, [cards]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);
}
